"""Define the controlled vocabulary used by documentation validation."""

SECTION_ORDER = ("Args", "Returns", "Raises")
SECTION_HEADERS = {f"{name}:" for name in SECTION_ORDER}
PLACEHOLDER_PHRASES = {
    "coordinate the multi-step",
    "for the active",
    "from the active",
    "result produced by",
    "side effects are applied",
    "used by this operation",
}
IMPERATIVE_VERBS = {
    "activate",
    "add",
    "allocate",
    "append",
    "apply",
    "approve",
    "assess",
    "attach",
    "begin",
    "bind",
    "build",
    "calculate",
    "capture",
    "check",
    "classify",
    "collect",
    "compare",
    "compose",
    "compute",
    "configure",
    "construct",
    "convert",
    "coordinate",
    "create",
    "deactivate",
    "define",
    "describe",
    "determine",
    "dispatch",
    "document",
    "ensure",
    "enter",
    "enumerate",
    "evaluate",
    "execute",
    "exit",
    "extract",
    "finish",
    "format",
    "generate",
    "handle",
    "hash",
    "hide",
    "implement",
    "initialize",
    "initialise",
    "inspect",
    "isolate",
    "link",
    "list",
    "load",
    "manage",
    "map",
    "normalize",
    "onboard",
    "parse",
    "persist",
    "plan",
    "prepare",
    "preserve",
    "preview",
    "produce",
    "provide",
    "publish",
    "read",
    "record",
    "register",
    "reject",
    "remove",
    "render",
    "report",
    "represent",
    "require",
    "resolve",
    "restore",
    "retire",
    "retrieve",
    "return",
    "round",
    "route",
    "run",
    "sanitise",
    "save",
    "scaffold",
    "score",
    "select",
    "show",
    "split",
    "stage",
    "start",
    "train",
    "transform",
    "update",
    "use",
    "validate",
    "verify",
    "write",
}
